<?xml version="1.0" encoding="UTF-8"?>
<!-- Generated by org.testng.reporters.JUnitReportReporter -->
<testsuite hostname="Jijos-Air.lan" failures="2" tests="13" name="com.TrainerManagementSystem.scripts.TestClassSignup" time="390.415" errors="0" timestamp="2022-03-20T15:25:43 GST" skipped="0">
  <testcase classname="com.TrainerManagementSystem.scripts.TestClassSignup" name="VerifySignUPMenuTCB2G70011" time="0.404"/>
  <system-out/>
  <testcase classname="com.TrainerManagementSystem.scripts.TestClassSignup" name="VerifySignUpTCB2G70012" time="9.836"/>
  <system-out/>
  <testcase classname="com.TrainerManagementSystem.scripts.TestClassSignup" name="VerifySignUpwithoutCourseTCB2G70023" time="37.132">
    <failure message="" type="java.lang.AssertionError">
      <![CDATA[java.lang.AssertionError: 
at org.testng.AssertJUnit.fail(AssertJUnit.java:65)
at org.testng.AssertJUnit.assertTrue(AssertJUnit.java:23)
at org.testng.AssertJUnit.assertTrue(AssertJUnit.java:33)
at com.TrainerManagementSystem.scripts.TestClassSignup.VerifySignUpwithoutCourseTCB2G70023(TestClassSignup.java:269)
at java.base/jdk.internal.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
at java.base/jdk.internal.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:78)
at java.base/jdk.internal.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
at java.base/java.lang.reflect.Method.invoke(Method.java:567)
at org.testng.internal.MethodInvocationHelper.invokeMethod(MethodInvocationHelper.java:133)
at org.testng.internal.TestInvoker.invokeMethod(TestInvoker.java:598)
at org.testng.internal.TestInvoker.invokeTestMethod(TestInvoker.java:173)
at org.testng.internal.MethodRunner.runInSequence(MethodRunner.java:46)
at org.testng.internal.TestInvoker$MethodInvocationAgent.invoke(TestInvoker.java:824)
at org.testng.internal.TestInvoker.invokeTestMethods(TestInvoker.java:146)
at org.testng.internal.TestMethodWorker.invokeTestMethods(TestMethodWorker.java:146)
at org.testng.internal.TestMethodWorker.run(TestMethodWorker.java:128)
at java.base/java.util.ArrayList.forEach(ArrayList.java:1511)
at org.testng.TestRunner.privateRun(TestRunner.java:794)
at org.testng.TestRunner.run(TestRunner.java:596)
at org.testng.SuiteRunner.runTest(SuiteRunner.java:377)
at org.testng.SuiteRunner.access$000(SuiteRunner.java:28)
at org.testng.SuiteRunner$SuiteWorker.run(SuiteRunner.java:418)
at org.testng.internal.thread.ThreadUtil.lambda$execute$0(ThreadUtil.java:64)
at java.base/java.util.concurrent.FutureTask.run(FutureTask.java:264)
at java.base/java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1130)
at java.base/java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:630)
at java.base/java.lang.Thread.run(Thread.java:831)
]]>
    </failure>
  </testcase> <!-- VerifySignUpwithoutCourseTCB2G70023 -->
  <system-out/>
  <testcase classname="com.TrainerManagementSystem.scripts.TestClassSignup" name="VerifyValidNameTCB2G70021" time="34.410"/>
  <system-out/>
  <testcase classname="com.TrainerManagementSystem.scripts.TestClassSignup" name="VerifyInvalidNameTCB2G70022" time="33.986"/>
  <system-out/>
  <testcase classname="com.TrainerManagementSystem.scripts.TestClassSignup" name="VerifyInvalidPhoneUsingStringsTCB2G70016" time="34.154"/>
  <system-out/>
  <testcase classname="com.TrainerManagementSystem.scripts.TestClassSignup" name="VerifyInvalidPhoneTCB2G70015" time="34.193"/>
  <system-out/>
  <testcase classname="com.TrainerManagementSystem.scripts.TestClassSignup" name="VerifyInvalidEmailTCB2G70020" time="34.069"/>
  <system-out/>
  <testcase classname="com.TrainerManagementSystem.scripts.TestClassSignup" name="VerifyValidEmailTCB2G70019" time="33.939"/>
  <system-out/>
  <testcase classname="com.TrainerManagementSystem.scripts.TestClassSignup" name="VerifyPasParameterTCB2G70086" time="35.933"/>
  <system-out/>
  <testcase classname="com.TrainerManagementSystem.scripts.TestClassSignup" name="VerifyEnteredSamePassTCB2G70017" time="34.078"/>
  <system-out/>
  <testcase classname="com.TrainerManagementSystem.scripts.TestClassSignup" name="VerifyEnteredDiffPassTCB2G70018" time="34.307"/>
  <system-out/>
  <testcase classname="com.TrainerManagementSystem.scripts.TestClassSignup" name="ListCourseTCB2G70013" time="33.974">
    <failure message="expected:&lt;4&gt; but was:&lt;6&gt;" type="java.lang.AssertionError">
      <![CDATA[java.lang.AssertionError: expected:<4> but was:<6>
at org.testng.AssertJUnit.fail(AssertJUnit.java:65)
at org.testng.AssertJUnit.failNotEquals(AssertJUnit.java:468)
at org.testng.AssertJUnit.assertEquals(AssertJUnit.java:88)
at org.testng.AssertJUnit.assertEquals(AssertJUnit.java:318)
at org.testng.AssertJUnit.assertEquals(AssertJUnit.java:328)
at com.TrainerManagementSystem.scripts.TestClassSignup.ListCourseTCB2G70013(TestClassSignup.java:100)
at java.base/jdk.internal.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
at java.base/jdk.internal.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:78)
at java.base/jdk.internal.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
at java.base/java.lang.reflect.Method.invoke(Method.java:567)
at org.testng.internal.MethodInvocationHelper.invokeMethod(MethodInvocationHelper.java:133)
at org.testng.internal.TestInvoker.invokeMethod(TestInvoker.java:598)
at org.testng.internal.TestInvoker.invokeTestMethod(TestInvoker.java:173)
at org.testng.internal.MethodRunner.runInSequence(MethodRunner.java:46)
at org.testng.internal.TestInvoker$MethodInvocationAgent.invoke(TestInvoker.java:824)
at org.testng.internal.TestInvoker.invokeTestMethods(TestInvoker.java:146)
at org.testng.internal.TestMethodWorker.invokeTestMethods(TestMethodWorker.java:146)
at org.testng.internal.TestMethodWorker.run(TestMethodWorker.java:128)
at java.base/java.util.ArrayList.forEach(ArrayList.java:1511)
at org.testng.TestRunner.privateRun(TestRunner.java:794)
at org.testng.TestRunner.run(TestRunner.java:596)
at org.testng.SuiteRunner.runTest(SuiteRunner.java:377)
at org.testng.SuiteRunner.access$000(SuiteRunner.java:28)
at org.testng.SuiteRunner$SuiteWorker.run(SuiteRunner.java:418)
at org.testng.internal.thread.ThreadUtil.lambda$execute$0(ThreadUtil.java:64)
at java.base/java.util.concurrent.FutureTask.run(FutureTask.java:264)
at java.base/java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1130)
at java.base/java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:630)
at java.base/java.lang.Thread.run(Thread.java:831)
]]>
    </failure>
  </testcase> <!-- ListCourseTCB2G70013 -->
  <system-out/>
</testsuite> <!-- com.TrainerManagementSystem.scripts.TestClassSignup -->
